version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USER_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_USER_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_USER_PASSWORD}
    links:
      - mongo
    depends_on:
      - mongo

  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER_USER: ${MONGO_USER_USER}
      MONGO_USER_PASSWORD: ${MONGO_USER_PASSWORD}
      MONGO_URL: mongodb://mongo:27017
    links:
      - mongo
    depends_on:
      - mongo